# Generated by Django 3.0.3 on 2020-03-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='images/avatar_2x.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman'), ('Unknown', 'Unknown')], default='Unknown', max_length=10, null=True),
        ),
    ]
